spring:
  datasource:
    username: local
    password: local
    url: jdbc:postgresql://localhost:5432/spring_yolo
  jpa:
    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format-sql: true
  flyway:
    schemas: migrations
    locations: classpath:migration
